name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pipenv
        run: pip install pipenv
      - name: Install dependencies
        run: pipenv install --dev && pip install pytest
      # You can test your matrix by printing the current Python version
      - name: Run the tests with pytest
        run: pipenv run make test
        env:
          NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
